.TH "TILDA" "1" "June 2008" "tilda 0.09.6" "User Commands"
.SH "NAME"
tilda \- first person shooter console likeness terminal
.SH "DESCRIPTION"
\fBTilda\fR is a terminal emulator taking after the likeness of many classic
terminals from first person shooter games, Quake, Doom and Half\-Life 
(to name a few), where the terminal has no border and is hidden from 
the desktop until a key is pressed.
.SS "Usage:"
.IP 
tilda [OPTION...]
.SS "Help Options:"
.TP 
\fB\-?\fR, \fB\-\-help\fR
Show help options
.TP 
\fB\-\-help\-all\fR
Show all help options
.TP 
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP 
\fB\-a\fR, \fB\-\-antialias\fR
Use Antialiased Fonts
.TP 
\fB\-b\fR, \fB\-\-background\-color\fR
Set the background color
.TP 
\fB\-c\fR, \fB\-\-command\fR
Run a command at startup
.TP 
\fB\-h\fR, \fB\-\-hidden\fR
Start Tilda hidden
.TP 
\fB\-f\fR, \fB\-\-font\fR
Set the font to the following string
.TP 
\fB\-l\fR, \fB\-\-lines\fR
Scrollback Lines
.TP 
\fB\-s\fR, \fB\-\-scrollbar\fR
Use Scrollbar
.TP 
\fB\-t\fR, \fB\-\-transparency\fR
Opaqueness: 0\-100%
.TP 
\fB\-v\fR, \fB\-\-version\fR
Print the version, then exit
.TP 
\fB\-w\fR, \fB\-\-working\-dir\fR
Set Initial Working Directory
.TP 
\fB\-x\fR, \fB\-\-x\-pos\fR
X Position
.TP 
\fB\-y\fR, \fB\-\-y\-pos\fR
Y Position
.TP 
\fB\-B\fR, \fB\-\-image\fR
Set Background Image
.TP 
\fB\-C\fR, \fB\-\-config\fR
Show Configuration Wizard
.TP 
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH "COPYRIGHT"
Copyright \(co 2005,2008 Tristan Sloughter (sloutri@iit.edu)
.br 
Copyright \(co 2005,2008 Ira W. Snyder (tilda@irasnyder.com)
.br 
Copyright \(co 2007,2008 Ken Dreyer (kdreyer@chicagolug.org)
.PP 
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. See the file COPYING for details.
.SH "SEE ALSO"
The full documentation for
.B tilda
is maintained as a Texinfo manual.  If the
.B info
and
.B tilda
programs are properly installed at your site, the command
.IP 
.B info tilda
.PP 
should give you access to the complete manual.
.SH "BUGS"
Please report it using
.B "reportbug tilda"
.SH "AUTHOR"
Davide Truffa <davide@catoblepa.org> wrote this manpage for
inclusion on the Debian Project but it could be used for others.
