/*
 * This is an extremely simple converter for the Tilda-0.9.4 and less
 * key format to the new Tilda-0.9.5 key format, which is the standard
 * key format used throughout GNOME, as far as I can tell.
 *
 * When the program is done running, the converted key string, in the
 * new format, will be in the variable new_keystr.
 */

/* The source will be automatically generated by lex */

#ifndef TILDA_KEY_CONVERTOR_H
#define TILDA_KEY_CONVERTOR_H

/* NOTE: Don't forget to free() the returned char*! */
char *upgrade_key_to_095 (const char *old_key);

#endif /* TILDA_KEY_CONVERTOR_H */

