
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "tilda-enum-types.h"
/* enumerations from "./src/tilda-search-box.h" */
#include "./src/tilda-search-box.h"
GType
tilda_search_direction_get_type (void)
{
    static GType the_type = 0;

    if (the_type == 0)
    {
        static const GEnumValue values[] = {
            { SEARCH_FORWARD,
              "SEARCH_FORWARD",
              "forward" },
            { SEARCH_BACKWARD,
              "SEARCH_BACKWARD",
              "backward" },
            { 0, NULL, NULL }
        };
        the_type = g_enum_register_static (
                g_intern_static_string ("TildaSearchDirection"),
                values);
    }
    return the_type;
}

/* Generated data ends here */

