
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef TILDA_ENUM_TYPES_H
#define TILDA_ENUM_TYPES_H

#include <glib-object.h>

G_BEGIN_DECLS
/* Enumerations from "./src/tilda-search-box.h" */
#define TILDA_TYPE_SEARCH_DIRECTION    (tilda_search_direction_get_type())
GType tilda_search_direction_get_type  (void) G_GNUC_CONST;
G_END_DECLS

#endif

/* Generated data ends here */

